apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: Bottlerocket
  role: ${split("/", module.eks_blueprints_addons.karpenter.node_iam_role_arn)[1]}
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: ${module.eks.cluster_name}
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: ${module.eks.cluster_name}
  tags:
    karpenter.sh/discovery: ${module.eks.cluster_name}
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        encrypted: true
        kmsKeyID: ${module.ebs_kms_key.key_arn}
        deleteOnTermination: true
        volumeSize: 2Gi
    - deviceName: /dev/xvdb
      ebs:
        encrypted: true
        kmsKeyID: ${module.ebs_kms_key.key_arn}
        deleteOnTermination: true
        volumeSize: 20Gi